name: Electron build/release

on:
  push:
  workflow_call:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build Electron app with electron-builder
        run: |
          cd taxonium_electron
          yarn install
          yarn make --arch universal
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: List output
        run: |
          cd taxonium_electron
          cd out/make/
          find .

      - name: Store artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: taxonium_electron/out/make/Taxonium-0.0.0-universal.dmg

  build-win:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build Electron app with electron-builder
        run: |
          cd taxonium_electron
          yarn install
          yarn make --win --arch=x64

      - name: List output
        run: |
          cd taxonium_electron
          cd out/make/squirrel.windows/x64
          dir
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Store artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: taxonium_electron/out/make/squirrel.windows/x64/Taxonium-0.0.0 Setup.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build Electron app with electron-builder
        run: |
          cd taxonium_electron
          yarn install
          yarn make --linux --arch=x64
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: List output
        run: |
          cd taxonium_electron
          cd out/make
          find .

      - name: Store artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: taxonium_electron/out/make/deb/x64/taxonium_0.0.0_amd64.deb

      - name: Store artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: taxonium_electron/out/make/rpm/x64/Taxonium-0.0.0-1.x86_64.rpm
  deploy-artifacts:
    runs-on: ubuntu-latest
    needs: [build-linux, build-win, build-mac]
    steps:
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: "artifacts/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: latest
