name: Integration Test

on:
  repository_dispatch:
  workflow_dispatch:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    uses: ./.github/workflows/frontend-test.yml
  python:
    uses: ./.github/workflows/python-test.yml
  # selenium:
  #   needs: [build, python]
  #   uses: ./.github/workflows/selenium-test.yml
